language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2.1

addons:
  postgresql: "9.4"

before_script:
  - psql -c "create database bookanook_test;" -U postgres
  - cp config/social_keys.yml.sample config/social_keys.yml
  - RAILS_ENV=test bundle exec rake --trace db:migrate
